server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/vote_authdb
    username: postgres
    password: kigali45
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    function:
      # ✅ Explicitly define all functional beans
      definition: voterCreationSucceeded;voterCreationFailed;voterUpdateSucceeded;voterUpdateFailed;userCreated;userUpdated;userDeleted;
                  candidateCreation;candidateCreationSucceeded;candidateCreationFailed;candidateUpdateSucceeded;candidateUpdateFailed

    stream:
      bindings:
        # ------------------ User events ------------------
        userCreated-out-0:
          destination: user-created
          contentType: application/json

        userUpdated-out-0:
          destination: user-updated
          contentType: application/json

        userDeleted-out-0:
          destination: user-deleted
          contentType: application/json

        # ------------------ Voter events feedback ------------------
        voterCreationSucceeded-in-0:
          destination: voter-creation-succeeded
          group: auth-service-voter-succeeded
          contentType: application/json


        voterCreationFailed-in-0:
          destination: voter-creation-failed
          group: auth-service-voter-failed
          contentType: application/json

        
        voterUpdateSucceeded-in-0:
          destination: voter-update-succeeded
          group: auth-service-voter-update-succeeded
          contentType: application/json

        voterUpdateFailed-in-0:
          destination: voter-update-failed
          group: auth-service-voter-update-failed
          contentType: application/json
        #=========================================================================

        # ------------------ Candidate events ------------------
        candidateCreated-out-0:
          destination: candidate-created
          contentType: application/json

        candidateUpdated-out-0:
          destination: candidate-updated
          contentType: application/json

        # ------------------ Candidate events feedback ------------------
        candidateCreationSucceeded-in-0:
          destination: candidate-creation-succeeded
          group: auth-service-candidate-succeeded
          contentType: application/json


        candidateCreationFailed-in-0:
          destination: candidate-creation-failed
          group: auth-service-candidate-failed
          contentType: application/json

        candidateUpdateSucceeded-in-0:
          destination: candidate-update-succeeded
          group: auth-service-candidate-update-succeeded
          contentType: application/json

        candidateUpdateFailed-in-0:
          destination: candidate-update-failed
          group: auth-service-candidate-update-failed
          contentType: application/json


      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          configuration:
            spring.json.trusted.packages: com.online.voting.events

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    kafka:
      enabled: true
    db:
      enabled: true

logging:
  level:
    org.springframework.cloud.stream: DEBUG
    org.springframework.integration: DEBUG
